stages:
  - cleanup

cleanup_subbranches:
  stage: cleanup
  only:
    - master # Run only when changes are pushed to the master branch
  script:
    - echo "Git setting"
    - git remote remove origin
    - git remote add origin https://$GITLAB_USERNAME:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - echo "Fetching all remote branches..."
    - git fetch --prune
    - echo "Listing and deleting all subbranches..."
    - |
      branches=$(git branch -r | grep -v 'origin/HEAD' | grep -v 'origin/master' | sed 's/origin\///')
      for branch in $branches; do
        echo "Deleting branch $branch"
        git push origin --delete $branch || echo "Failed to delete $branch"
      done
