image: atlassian/default-image:4

clone:
  enabled: true
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: 'Mirror repository to GitLab'
          script:
            - pwd && ls -ld
            - git push --mirror git@gitlab.com:devsecopsbr1/docker.git
