image: alpine

pipelines:
  default:
    - step:
        name: "Slack notification"
        script:
          - pipe: atlassian/slack-notify:1.0.0
            variables:
              WEBHOOK_URL: $WEBHOOK_URL
              MESSAGE: 'Hello, world!'
    - step:
        name: "Docker HUB Authentication"
        script:
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
options:
  docker: true