image: alpine

pipelines:
  default:
    - step:
        script:
          - echo "Docker HUB authentication"
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - step:
        script:
          - echo "Building image..."
options:
  docker: true