version: '3.9'

services:

  bitbucket:
    image: webhookrelay/webhookrelayd:latest
    network_mode: host
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    restart: always
    command:
      - --mode
      - tunnel
    env_file:
      - ./.env/bitbucket.env

  github:
    image: webhookrelay/webhookrelayd:latest
    network_mode: host
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 0
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    restart: always
    command:
      - --mode
      - tunnel
    env_file:
      - ./.env/github.env

<<<<<<< HEAD
networks: 
=======
networks:
>>>>>>> CU-initial
  docker2docker:
    external: true
