version: "3.6"

services:
  server:
    image: docker.io/gitea/gitea:1.22.6
    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=docker2docker
        - traefik.http.routers.gitea.entrypoints=web,websecure
        - traefik.http.routers.gitea.rule=Host(`gitea.docker.local`)
        - traefik.http.services.gitea.loadbalancer.server.port=3000
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - USER_UID=1000
      - USER_GID=1000
    env_file: 
      - ./.secrets/gitea.env
    networks:
      - docker2docker
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - "3000:3000"
      - "222:22"

networks:
  docker2docker:
      external: true

volumes:
  gitea:
    external: true

