version: "3.9"

services:

  db:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: '0.25'
          memory: 20M
    env_file:
      - ./.env/postgre.env
    expose:
      - 5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - docker2docker

  server_bitbucket:
    image: drone/drone:2
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=docker2docker
        - traefik.docker.lbswarm=true
        - traefik.http.routers.droneci.entrypoints=web
        - traefik.http.routers.droneci.rule=Host(`droneci.local`) || PathPrefix(`/droneci`)
        - traefik.http.services.droneci.loadbalancer.server.port=80
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    env_file: 
      - ./.env/bitbucket.env
    expose:
      - 80
      - 443
    restart: always
    volumes:
      - drone-server-data:/var/lib/drone/
    networks:
      - docker2docker

  agent:
    image: drone/drone-runner-docker:1
    command: agent
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    env_file:
      - ./.env/agents.env
    expose: 
      - 3000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - docker2docker

volumes:
  drone-server-data:
    external: true
    name:  drone-config
  db:
    external: true
    name: postgres-database

networks: 
  docker2docker:
    external: true
