version: "3.9"

services:

  db:
    image: postgres
    deploy:
      labels:
        - traefik.enable=false
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: '0.25'
          memory: 20M
    env_file:
      - ./.env/postgre.env
      - ./.secrets/postgre.env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - docker2docker

  server_bitbucket:
    image: drone/drone:2
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=docker2docker
        - traefik.http.routers.bitbucket.entrypoints=web,websecure
        - traefik.http.routers.bitbucket.rule=Host(`droneci-bb.local`)
        - traefik.http.services.bitbucket.loadbalancer.server.port=80
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    env_file: 
      - ./.env/bitbucket.env
      - ./.secrets/bitbucket.env
    restart: always
    volumes:
      - drone-server-data:/var/lib/drone/
    networks:
      - docker2docker

  server_github:
    image: drone/drone:2
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=docker2docker
        - traefik.docker.lbswarm=true
        - traefik.http.routers.github.entrypoints=web,websecure
        - traefik.http.routers.github.rule=Host(`droneci-gh.local`)
        - traefik.http.services.github.loadbalancer.server.port=80
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    env_file: 
      - ./.env/github.env
    restart: always
    volumes:
      - drone-server-data:/var/lib/drone/
    networks:
      - docker2docker

  runner:
    image: drone/drone-runner-docker:1
    command: agent
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=docker2docker
        - traefik.docker.lbswarm=true
        - traefik.http.routers.dashboard.entrypoints=web
        - traefik.http.routers.dashboard.rule=Host(`droneci.local`) && PathPrefix(`/dashboard`)
        - traefik.http.services.dashboard.loadbalancer.server.port=3000
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    env_file:
      - ./.env/runner.env
      - ./.secrets/runner.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - docker2docker

volumes:
  drone-server-data:
    external: true
    name:  drone-config
  db:
    external: true
    name: postgres

networks: 
  docker2docker:
    external: true
