apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  labels:
    app: coredns_tls
data:
  Corefile: |
    .:53 {
      errors
      any
      log
      health {
         lameduck 5s
      }
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
         pods insecure
         fallthrough in-addr.arpa ip6.arpa
         ttl 30
      }
      forward . tls://1.1.1.1 tls://1.0.0.1 {
         health_check 10s
         prefer_udp
         max_fails 10
         expire 30s
         health_check 60s
      }
      prometheus :9153
      cache 30
      loop
      reload
      loadbalance
     }
     tls://.:853 {
         forward . 1.1.1.1:53
         log
     }


