version: '3.3'

services:

  traefik:
    image: traefik
    environment:
      HOSTNAME: traefik
      SERVICE_NAME: traefik
      SERVICE_TAGS: lb, proxy
      CONSUL_HTTP_TOKEN: 01f47f9e-f989-966b-9acc-f88fde2e7f9f
    labels:
      - "SERVICE_IGNORE=false"      
      - "traefik.enable=false"   
    command:
      - "--api=true"
      - "--api.debug=true"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.network=docker2docker"
      - "--providers.docker.watch=true"
      - "--providers.file.debugloggeneratedtemplate=true"
      - "--providers.file.watch=true"
      - "--metrics.prometheus=true"
      - "--tracing.jaeger=true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker2docker
  
networks:
    docker2docker:
        external: true
