version: '3.9'

services:

  clients:
    image: consul:latest
    labels:
      - "SERVICE_IGNORE=false"
      # Traefik proxy settings
      - traefik.enable=false
    command: "agent -retry-join server_bootstrap"
    depends_on:
      - server_bootstrap
    volumes:
      - "./client_config/config.json:/consul/config/config.json:rw"
    deploy:
      replicas: 3
      mode: replicated
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    networks:
      - docker2docker

  servers:
    image: consul:latest
    labels:
      - "SERVICE_IGNORE=false"
      # Traefik proxy settings
      - "traefik.enable=true"
      - "traefik.docker.lbswarm=false"
      - "traefik.docker.network=docker2docker"
      - "traefik.tcp.routers.consul-servers.entrypoints=web"
      - "traefik.tcp.routers.consul-servers.rule=Host(`consul-server.docker.local`)"
      - "traefik.tcp.services.consul-servers.loadbalancer.server.port=8500"
    command: "agent -server -retry-join server_bootstrap"
    depends_on:
      - server_bootstrap
    volumes:
      - "./server_config/config.json:/consul/config/config.json:rw"
    deploy:
      replicas: 2
      mode: replicated
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    networks:
      - docker2docker
      
  server_bootstrap:
    image: consul:latest
    environment:
      CONSUL_UI_BETA: "true"
    working_dir: /consul/config/
    labels:
      - "SERVICE_IGNORE=false"
      # Traefik proxy settings
      - traefik.enable=false
    command: "agent -server"
    volumes:
      - "./bootstrap_config/:/consul/config:rw"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    networks:
      - docker2docker

volumes:
  consul: 
    external: true

networks:
    docker2docker:
        external: true
