version: '3.9'

services:

  clients:
    image: consul:1.15.4
    command: "agent -retry-join server_bootstrap"
    depends_on:
      - server_bootstrap
    volumes:
      - "./client_config/config.json:/consul/config/config.json:rw"
    deploy:
      labels:
        - "SERVICE_IGNORE=false"
        # Traefik proxy settings
        - traefik.enable=false
      replicas: 2
      mode: replicated
      endpoint_mode: vip
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    networks:
      - docker2docker

  servers:
    image: consul:1.15.4
    command: "agent -server"
    depends_on:
      - server_bootstrap
    volumes:
      - "./server_config/config.json:/consul/config/config.json:rw"
    deploy:
      labels:
        - "SERVICE_IGNORE=false"
        # Traefik proxy settings
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.docker.network=docker2docker"
        - "traefik.http.routers.consul-servers.entrypoints=web"
        - "traefik.http.routers.consul-servers.rule=Host(`consul.docker.local`)"
        - "traefik.http.services.consul-servers.loadbalancer.server.port=8500"
      replicas: 2
      mode: replicated
      endpoint_mode: vip
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    networks:
      - docker2docker
<<<<<<< HEAD
      
=======

>>>>>>> CU-initial
  server_bootstrap:
    image: consul:1.15.4
    environment:
      CONSUL_UI_BETA: "true"
    working_dir: /consul/config/
    command: "agent -server"
    volumes:
      - "./bootstrap_config/:/consul/config:rw"
    deploy:
      labels:
        - "SERVICE_IGNORE=false"
        # Traefik proxy settings
        - traefik.enable=false
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
    ports:
      - 8500:8500
    networks:
      - docker2docker

volumes:
<<<<<<< HEAD
  consul: 
=======
  consul:
>>>>>>> CU-initial
    external: true

networks:
    docker2docker:
        external: true
