version: '3.9'

services:

  server:
    image: gocd/gocd-server
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=docker2docker"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.teamcity.entrypoints=web"
        - traefik.http.routers.teamcity.rule=Host(`gocd.local`)
        - traefik.http.services.teamcity.loadbalancer.server.port=8153
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 500M
    expose:
      - "8153:8153"
    volumes:
      - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
    networks:
      - docker2docker

  agent1:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go

  agent2:
    image: gocd/gocd-agent-ubuntu-16.04:v17.9.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go

networks:
  docker2docker:
    external: true

volumes:
  config:
    external: true
    name: gocd-configs
  logs:
    external: true
    name: gocd-logs
