version: '3.9'

services:

  server:
    image: gocd/gocd-server:v21.2.0
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=docker2docker"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.gocd.entrypoints=web,websecure"
        - traefik.http.routers.gocd.rule=Host(`gocd.docker.local`)
        - traefik.http.services.gocd.loadbalancer.server.port=8153
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 500M
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata/server:/godata
    networks:
      - docker2docker

  agent1:
    image:  gocd/gocd-agent-alpine-3.13:v21.2.0
    environment:
      GO_SERVER_URL: http://gocd_server:8153/go
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 500M
    volumes:
      - ./godata/agent/autoregister.properties:/var/lib/go-agent/config/
    networks:
      - docker2docker

  # agent2:
  #   image:  gocd/gocd-agent-docker-dind:v21.2.0
  #   environment:
  #     AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
  #     GO_SERVER_URL: http://gocd_server:8153/go
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 500M
  #   networks:
  #     - docker2docker

networks:
  docker2docker:
    external: true

volumes:
  config:
    external: true
    name: gocd-configs
  pgdata:
    external: true
    name: postgres
  logs:
    external: true
    name: gocd-logs
