version: '3.9'

services:

  server:
    image: vault:latest
    working_dir: /vault/config/
    environment:
      VAULT_ADDR: http://server:8200
      VAULT_ROOT_TOKEN_ID: protectme
      SERVICE_NAME: vault
      SERVICE_TAGS: vault, seal, encrypt
    labels:
      #  Traefik proxy settings
      - "traefik.enable=true"
      - "traefik.docker.lbswarm=false"
      - "traefik.docker.network=docker2docker"
      - "traefik.tcp.routers.vault-server.entrypoints=web"
      - "traefik.tcp.routers.vault-server.rule=Host(`vault.docker.local`)"
      - "traefik.tcp.services.vault-server.loadbalancer.server.port=8200"
    volumes:
      - ./config/:/vault/config/:rw
    command: "vault server -config /vault/config/ -log-level=debug"
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1G
    ports:
      - 8200:8200
    networks:
      - docker2docker
      
networks:
  docker2docker:
      external: true
