version: "3.9"

services:

  server:
    image: harness/harness
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.lbswarm=true
        - traefik.docker.network=docker2docker
        - traefik.http.routers.gitness.entrypoints=web,websecure
        - traefik.http.routers.gitness.rule=Host(`harness.docker.local`)
        - traefik.http.services.gitness.loadbalancer.server.port=3000
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitness-data:/data
    environment:
      - GITNESS_URL_BASE=http://harness.docker.local
      # Gitness admin credentials
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=admin12345
      # Postgres credentials settings
      - GITNESS_DATABASE_DRIVER=postgres
      - GITNESS_DATABASE_DATASOURCE=postgres://root:${DOCKER_SECRET_DB}@db_postgres:5432/gitness?sslmode=disable
    env_file:
      - ./envs/settings.env
    networks:
      - docker2docker

volumes:
  gitness-data:
    external: true

networks:
  docker2docker:
    external: true
