version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - docker2docker

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    expose:
      - 9000
      - 8000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - traefik.docker.lbswarm=true
        - traefik.docker.network=docker2docker
        - "traefik.http.routers.portainer.entrypoints=web"
        - "traefik.http.routers.portainer.rule=Host(`portainer-ui.local`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - docker2docker
    volumes:
      - portainer_data:/data

networks:
  docker2docker:
    external: true

volumes:
  portainer_data:
