version: "3.8"
services:

  forward:
    image: "coredns/coredns"
    deploy:
     replicas: 1
     labels:
       com.n26.description: "CoreDNS TLS"
       com.n26.service: "CoreDNS"
       com.n26.department: "SRE"
     update_config:
       parallelism: 1
       failure_action: rollback
       delay: 30s
     restart_policy:
       condition: any
       delay: 5s
       window: 120s
     resources:
       limits:
         memory: 1G  
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "./certs:/etc/coredns/certs"
      - "./config/docker/coredns_forward:/etc/coredns/Corefile"
    command: -conf /etc/coredns/Corefile -dns.port=53
    networks:
      - docker2docker

  tls:
    image: "coredns/coredns"
    deploy:
     replicas: 1
     labels:
       com.n26.description: "CoreDNS TLS"
       com.n26.service: "CoreDNS"
       com.n26.department: "SRE"
     update_config:
       parallelism: 1
       failure_action: rollback
       delay: 30s
     restart_policy:
       condition: any
       delay: 5s
       window: 120s
     resources:
       limits:
         memory: 1G  
    ports:
      - "853:853"
    volumes:
      - "./certs:/etc/coredns/certs"
      - "./config/docker/coredns_tls:/etc/coredns/Corefile"
    command: -conf /etc/coredns/Corefile -dns.port=853
    networks:
      - docker2docker

networks:
  docker2docker:
      external: true